#!/usr/bin/env bash
set -euo pipefail

[[ -d /var/halfpipe/shared-cache ]] && export GOMODCACHE="/var/halfpipe/shared-cache/gomodcache"

CGO_ENABLED=0 go build webserver.go

echo "Finished. built ./webserver"
